[workspace]
authors = ["Guoxuan Xu <g7xu@ucsd.edu>"]
channels = ["conda-forge"]
name = "25fa-dsc180a-team1"
platforms = ["osx-64", "osx-arm64", "linux-64", "linux-aarch64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.11.*"
sqlalchemy = ">=2.0.43,<3"
psycopg = ">=3.2.9,<4"
psycopg2-binary = ">=2.9.9,<3"
python-dotenv = ">=1.1.1,<2"
jupyterlab = ">=4.4.9,<5"
ipykernel = ">=6.30.1,<7"
pandas = ">=2.3.3,<3"

[pypi-dependencies]
mimiciii-db = { path = ".", editable = true }
